export const data = {
  name: 'Jimmy Chamberlin',
  title: 'Operations Architect',
  tagline: ['Building systems', 'that scale.'],
  subtitle: 'Business Operations Leader · 16 Years · BBA',
  available: true,
  availableText: 'AVAILABLE FOR HIRE',
  email: 'jimmy@jimmychamberlin.com',
  linkedin: 'https://linkedin.com/in/jimmychamberlin',
  github: 'https://github.com/tru0blu0',
  location: 'United States',
  // Canonical site URL — update here when domain changes.
  // Used by Footer, JSON-LD, and any component that needs the full URL.
  siteUrl: 'https://tru0blu0.github.io/jimmy-chamberlin-portfolio',

  stats: [
    { value: 16, suffix: '+', label: 'Years Operations Leadership', prefix: '' },
    { value: 4, suffix: '', label: 'Industries Mastered', prefix: '' },
    { value: 85, suffix: '%', label: 'Average Process Efficiency Gain', prefix: '' },
    { value: 12, suffix: 'M', label: 'Operational Cost Savings Driven', prefix: '$' },
  ],

  experience: [
    {
      domain: 'Business DevOps',
      role: 'Senior Operations Leader',
      period: '2018–Present',
      icon: '⚙',
    },
    {
      domain: 'Logistics Operations',
      role: 'Supply Chain & Distribution Manager',
      period: '2015–2018',
      icon: '📦',
    },
    {
      domain: 'Restaurant Operations',
      role: 'Multi-Unit Operations Director',
      period: '2012–2015',
      icon: '🍽',
    },
    {
      domain: 'Legal Operations',
      role: 'Legal Ops & Compliance Coordinator',
      period: '2010–2012',
      icon: '⚖',
    },
    {
      domain: 'IT Infrastructure',
      role: 'IT Operations Intern',
      period: '2008–2010',
      icon: '💻',
    },
  ],

  skills: [
    'Process Engineering',
    'Supply Chain Optimization',
    'Cross-Functional Leadership',
    'Business Intelligence',
    'KPI & OKR Frameworks',
    'Change Management',
    'Compliance & Risk',
    'Vendor Management',
    'Budget Forecasting',
    'ERP Systems',
    'Workforce Planning',
    'SOX & Audit Readiness',
  ],

  caseStudies: [
    {
      id: 'logistics',
      domain: 'LOGISTICS',
      headline: 'Rebuilt fulfillment pipeline',
      tagline: 'Reduced order-to-ship time by 62% in 6 months',
      problem: 'A regional 3PL was hemorrhaging clients due to 4–5 day order-to-ship cycles. Manual pick-ticket processes, no real-time inventory visibility, and three disconnected WMS platforms made every day a triage exercise.',
      approach: 'Mapped every handoff in the fulfillment flow. Identified 11 unnecessary approval steps. Consolidated to a single WMS, built live dashboards for floor supervisors, and implemented wave-picking sequences aligned to carrier cut-off times.',
      results: [
        { metric: '62%', label: 'Reduction in order-to-ship time' },
        { metric: '94%', label: 'On-time delivery rate (up from 71%)' },
        { metric: '$1.8M', label: 'Annual carrier penalty savings' },
        { metric: '3', label: 'Retained enterprise clients at risk of churn' },
      ],
    },
    {
      id: 'restaurant',
      domain: 'RESTAURANT / QSR',
      headline: 'Rebuilt multi-unit ops model',
      tagline: 'Turned 3 underperforming locations into top-10 systemwide',
      problem: 'Three QSR franchise locations in the bottom quartile systemwide — high turnover, labor cost at 36% of revenue, and food waste running 2x the brand standard. Each GM operated independently with no shared systems.',
      approach: 'Standardized labor scheduling templates, implemented a shared COGS tracking sheet across all three units, rebuilt onboarding from a 90-minute verbal rundown to a documented 5-day program. Created a weekly ops cadence across GMs.',
      results: [
        { metric: '36%→27%', label: 'Labor cost as % of revenue' },
        { metric: '48%', label: 'Reduction in management turnover' },
        { metric: 'Top 10', label: 'Systemwide ranking achieved within 18 months' },
        { metric: '$420K', label: 'Annualized food waste reduction' },
      ],
    },
    {
      id: 'legal',
      domain: 'LEGAL OPERATIONS',
      headline: 'Rebuilt contract & compliance workflow',
      tagline: 'Cut contract turnaround from 14 days to 3',
      problem: 'A mid-size professional services firm had a legal ops function that was a bottleneck. Contracts sat in email chains for weeks, approval routing was ad hoc, and audit prep required weeks of manual document assembly.',
      approach: 'Mapped the contract lifecycle end-to-end, identified that 80% of delays happened in two steps. Implemented a CLM tool, built standard templates for 90% of contract types, and automated approval routing for routine renewals.',
      results: [
        { metric: '14d → 3d', label: 'Average contract turnaround' },
        { metric: '80%', label: 'Reduction in legal team review time on routine contracts' },
        { metric: '$200K', label: 'First-year CLM ROI vs. outside counsel costs' },
        { metric: '100%', label: 'Audit-ready document retrieval within 24 hours' },
      ],
    },
  ],

  education: {
    degree: 'BBA — Business Administration',
    institution: 'University of Phoenix',
    year: '2014',
    focus: 'Operations Management & Business Strategy',
  },

  credibilityMarquee: [
    'Process Engineering',
    '·',
    'Supply Chain Optimization',
    '·',
    'Cross-Functional Leadership',
    '·',
    'Business Intelligence',
    '·',
    'KPI & OKR Frameworks',
    '·',
    'Change Management',
    '·',
    'Compliance & Risk',
    '·',
    'Vendor Management',
    '·',
    'Budget Forecasting',
    '·',
    'ERP Systems',
    '·',
    'Workforce Planning',
    '·',
    'SOX & Audit Readiness',
    '·',
    '16 Years Operations Leadership',
    '·',
    '4 Industries',
    '·',
    'BBA Business Administration',
    '·',
  ],

  approach: [
    {
      step: '01',
      title: 'Map before you move',
      description: 'Every engagement starts with process archaeology — understanding what actually happens, not what the org chart says happens.',
    },
    {
      step: '02',
      title: 'Instrument the work',
      description: 'You cannot improve what you cannot measure. I build measurement infrastructure before recommending changes.',
    },
    {
      step: '03',
      title: 'Fix the system, not the symptom',
      description: 'Most operational problems are structural. I design for root-cause elimination, not recurring patch jobs.',
    },
    {
      step: '04',
      title: 'Leave it self-sustaining',
      description: 'Improvements that depend on one person are not improvements. Every engagement ends with documentation, training, and handoff.',
    },
  ],
}
