export const data = {
  name: 'Jimmy Chamberlin',
  title: 'Operations Architect',
  tagline: ['Building systems', 'that scale.'],
  subtitle: 'Business Operations Leader · 16 Years · BBA',
  available: true,
  availableText: 'AVAILABLE FOR HIRE',
  email: 'jimmy@jimmychamberlin.com',
  linkedin: 'https://linkedin.com/in/jimmychamberlin',
  github: 'https://github.com/tru0blu0',
  location: 'United States',
  // Canonical site URL — update here when domain changes.
  // Used by Footer, JSON-LD, and any component that needs the full URL.
  siteUrl: 'https://tru0blu0.github.io/jimmy-chamberlin-portfolio',

  stats: [
    { value: 16, suffix: '+', label: 'Years Operations Leadership', prefix: '' },
    { value: 4,  suffix: '',  label: 'Industries Mastered',          prefix: '' },
    { value: 71, suffix: '%', label: 'Revenue Growth at Peak Engagement', prefix: '' },
    { value: 31.7, suffix: '%', label: 'COGS Held — 89 Consecutive Weeks', prefix: '' },
  ],

  experience: [
    {
      domain: 'Legal Operations',
      role: 'Legal Assistant',
      company: 'Kyser Law, PLC',
      period: 'Jan 2021 – Sep 2025',
      icon: '⚖',
    },
    {
      domain: 'Freight Logistics',
      role: 'Logistics & Transport Coordinator',
      company: 'J&J Freight Logistics, LLC',
      period: 'Feb 2017 – Mar 2020',
      icon: '🚚',
    },
    {
      domain: 'Restaurant / F&B Operations',
      role: 'Operations Manager',
      company: 'The Pointe Bar & Grill',
      period: 'May 2014 – Sep 2016',
      icon: '🍽',
    },
    {
      domain: 'IT Infrastructure',
      role: 'IT Intern',
      company: 'Mid-Michigan Community College',
      period: 'May 2009 – Jun 2010',
      icon: '💻',
    },
  ],

  skills: [
    'P&L Ownership',
    'COGS & Margin Control',
    'Vendor Spend Management',
    'Process Engineering',
    'TMS Implementation',
    'ELD & MDM Deployment',
    'Practice Management Systems',
    'FMCSA Compliance',
    'MLCC Compliance',
    'Cross-Border Operations',
    'Workforce Planning',
    'SOPs & Standards',
  ],

  caseStudies: [
    {
      id: 'logistics',
      domain: 'LOGISTICS',
      year: '2017–2020',
      headline: 'Built a freight brokerage from zero',
      tagline: '100% ELD compliance before federal mandate · MC-2979 broker authority · VehicHaul TMS',
      problem: 'J&J Auto Express decided to launch a licensed freight brokerage in Feb 2017 with nothing in place: no FMCSA broker authority, no TMS, no carrier network, fleet drivers still on paper HOS logs, and a single-customer dependency on DriveTime.',
      approach: 'Built the entire operational foundation: secured FMCSA MC-2979 broker authority, selected Samsung Tab A + BigRoad DashLink ELD + Samsung Knox MDM for fleet-wide compliance (beat the Dec 18, 2017 mandate), replaced AscendTMS with VehicHaul in July 2019 to eliminate double-entry bottleneck, built carrier onboarding with ePOD payment-term enforcement, and qualified the company as an SDDC DoD-certified carrier.',
      tags: ['ELD Compliance', 'TMS Implementation', 'FMCSA', 'Freight Brokerage', 'Cross-Border', 'SDDC DoD'],
      results: [
        { metric: '100%',    label: 'Fleet ELD compliance — beat Dec 18, 2017 federal mandate' },
        { metric: 'MC-2979', label: 'FMCSA broker authority — operational from Day 1' },
        { metric: 'Jul 2019',label: 'VehicHaul TMS go-live — replaced AscendTMS bottleneck' },
        { metric: '0',       label: 'Enforcement actions across 3 years of broker operations' },
      ],
    },
    {
      id: 'restaurant',
      domain: 'RESTAURANT / F&B',
      year: '2014–2016',
      headline: 'Turned operational chaos into a $1.25M engine',
      tagline: '+71% revenue growth · COGS held 31.7% for 89 consecutive weeks · 203 vendors reconciled',
      problem: 'The Pointe operated with no P&L system, no vendor controls, and no documented processes. Revenue sat at $734k and COGS ran unchecked at 36–42% with zero internal benchmarks, no invoice reconciliation, and no staffing model across 29 staff and 7 roles.',
      approach: 'Built the complete operational infrastructure: a 19-sheet Excel P&L, 30-category invoice ledger across 203 vendors, 89-week consecutive alcohol cost tracking, dual-vendor food distributor strategy (GFS + Sysco), SOPs for all 7 roles, and a 29-person staffing model — giving ownership the visibility to scale without losing cost discipline.',
      tags: ['P&L Ownership', 'COGS Reduction', 'Vendor Management', 'F&B Operations', 'SOPs', 'Excel P&L'],
      results: [
        { metric: '+71%',   label: 'Revenue growth — $734k → $1.25M (2013–2015)' },
        { metric: '31.7%',  label: 'Avg COGS held across 89 consecutive tracked weeks' },
        { metric: '$1.42M', label: 'Vendor spend tracked — 2,561 invoices reconciled' },
        { metric: '0',      label: 'MLCC compliance violations — full 28-month tenure' },
      ],
    },
    {
      id: 'legal',
      domain: 'LEGAL OPERATIONS',
      year: '2021–2025',
      headline: 'Owned the full legal ops & tech stack solo',
      tagline: '~20 concurrent matters · 7+ practice areas · 4+ years daily production · 0 e-filing rejections',
      problem: 'Kyser Law operated PracticePanther as a standalone, disconnected system — no Google Workspace sync, no Secure Client Portal, no integrated payment processing — across a caseload spanning 7+ practice areas with no standardized client onboarding SOP.',
      approach: 'Self-implemented the entire firm tech stack with no IT support: connected PracticePanther to Google Workspace (calendar/email sync), integrated Secure Client Portal for document exchange, configured LawPay for statutory-compliant billing, authored the client onboarding SOP, maintained ~20 concurrent active client files, prepared 5–10 MiFILE filings per week, and held Michigan Notary Public commission (active through Feb 2028).',
      tags: ['PracticePanther', 'Legal Ops', 'Practice Management', 'MiFILE E-Filing', 'LawPay', 'Michigan Notary'],
      results: [
        { metric: '~20',  label: 'Open client files managed concurrently' },
        { metric: '4+',   label: 'Years PracticePanther in daily production (2021–2025)' },
        { metric: '7+',   label: 'Practice areas supported simultaneously' },
        { metric: '0',    label: 'E-filing rejections across 4+ year tenure' },
      ],
    },
    {
      id: 'it',
      domain: 'IT / SYSTEMS',
      year: '2009–2010',
      headline: 'Automated multi-campus lab deployment from scratch',
      tagline: '300–400+ workstations · Monthly cadence · 8 scripts in Batch, VBScript & PowerShell',
      problem: 'Mid-Michigan Community College maintained 300+ networked lab workstations across 5+ labs on two campuses. Every semester required full software deployment and Windows Update cycles — previously administered machine-by-machine, requiring physical presence at each of 30–40 machines per lab.',
      approach: 'Designed and built a psexec-based remote deployment toolkit from scratch: list-driven batch scripts pushing software silently to entire lab groups from a single admin workstation, a VBScript WUA (Windows Update Agent) for programmatic patch search/download/install, WMI hardware control for CD-ROM management, and a modular script library (All Installers, Adobe Reader, Remote Run, Remote CMD). No prior playbook — built entirely from zero.',
      tags: ['Batch Scripting', 'VBScript/WMI', 'psexec', 'Remote Deployment', 'Systems Admin', 'PowerShell'],
      results: [
        { metric: '300–400+', label: 'Workstations addressable per deployment cycle' },
        { metric: 'Monthly',  label: 'Deployment cadence established — both campuses' },
        { metric: '8',        label: 'Scripts built (Batch, VBScript, PowerShell)' },
        { metric: '0',        label: 'Required physical presence on target machines' },
      ],
    },
  ],

  education: {
    degree: 'BBA — Business Administration',
    institution: 'Baker College, Jackson MI',
    year: 'Dec 2025',
    focus: 'Operations Management & Business Strategy',
  },

  credibilityMarquee: [
    'P&L Ownership',
    '·',
    'COGS & Margin Control',
    '·',
    'VehicHaul TMS',
    '·',
    'BigRoad ELD',
    '·',
    'Samsung Knox MDM',
    '·',
    'PracticePanther',
    '·',
    'LawPay',
    '·',
    'FMCSA Compliance',
    '·',
    'MLCC Compliance',
    '·',
    'ACE/ACI eManifest',
    '·',
    'MiFILE E-Filing',
    '·',
    'Michigan Notary Public',
    '·',
    'Google Workspace',
    '·',
    'Excel / VBA',
    '·',
    'psexec · VBScript',
    '·',
    '16 Years Operations Leadership',
    '·',
    'BBA · Baker College',
    '·',
  ],

  approach: [
    {
      step: '01',
      title: 'Document the AS-IS before touching anything',
      description: 'Every engagement starts with mapping what actually exists — the real process, not the org chart. I build the problem statement before proposing any solution.',
    },
    {
      step: '02',
      title: 'Build the measurement infrastructure first',
      description: 'I put tracking in place before making changes. Whether that\'s a 19-sheet Excel P&L, 89-week COGS log, or a TMS go-live date — you can\'t manage what you can\'t measure.',
    },
    {
      step: '03',
      title: 'Fix the system, not the symptom',
      description: 'Most operational problems are structural. I design for root-cause elimination — carrier onboarding that enforces ePOD compliance, invoice ledgers that make ACH auto-debits visible, SOPs that survive staff turnover.',
    },
    {
      step: '04',
      title: 'Leave it self-sustaining',
      description: 'Every engagement ends with documented SOPs, trained staff, and systems that run without me. The measure of success is that it holds after I\'m gone.',
    },
  ],
};
